Reference: https://www.tensorflow.org/versions/r0.12/get_started/basic_usage

### What are Tensor, Graph, Session, Variable?
1) A "tensor" is like a matrix but with an arbitrary number of dimensions. A 1-dimensional tensor is a vector. A 2-dimensions tensor is a matrix. And then you can have tensors with 3, 4, 5 or more dimensions.  
2) A graph defines the computation. It doesn’t compute anything, it doesn’t hold any values, it just defines the operations that you specified in your code.  
3) A session allows to execute graphs or part of graphs. It allocates resources (on one or more machines) for that and holds the actual values of intermediate results and variables.   
4) We define a graph with a variable and three operations: variable always returns the current value of our variable. initialize assigns a value, say 10, to that variable. assign assigns the new value, say 20, to that variable.   
5) To run any of the above three defined operations, we need to create a session for that graph. The session will also allocate memory to store the current value of the variable.   
6) Value of our variable is only valid within one session. If we try to query the value afterwards in a second session, TensorFlow will raise an error because the variable is not initialized there.   
7) Value of A variable is only valid within one session. If we try to query the value afterwards in a second session, TensorFlow will raise an error because the variable is not initialized there.   

### TensorFlow's "deferred execution" model
1) As Tensorflow is built for distributed computing, it has to know in advance what is to be computed. This is informed via Graph before the tasks are sent to various computers.   
2) Once the session is initiated and computations begin with Session.run, graph cannot be changed.   

### TensorFlow and Numpy are friends
1) When preparing the computation graph, you only manipulate TensorFlow tensors and commands such as tf.matmul, tf.reshape and so on.  
2) However, as soon as you execute a Session.run command, the values it returns are Numpy tensors, i.e. numpy.ndarray objects that can be consumed by Numpy and all the scientific comptation libraries based on it. That is how the real-time visualisation was built for this lab, using matplotlib, the standard Python plotting library, which is based on Numpy.

### TensorFlow overview
1) Computations are represented as GRAPHS   
2) Nodes in the graph are called OPS or Operations   
3) An op takes zero or more tensors, performs some computation and produces zero or more tensors   
4) TENSOR is a multi-dimensional array that stores data   
5) In a nutshell, TENSORFLOW GRAPH is a description of computations   
6) In order to perform computations, graph is launched in a SESSION   
7) Session places Graph Ops onto DEVICES such as cpu or gpu and provide METHODS to execute them   
8) These methods return tensors produced by ops as NUMPY NDARRAY in Python   
9) Tensorflow PROGRAMS have two phases:   
    (i) CONSTRUCTION phase that assembles graph (to represent a neural network) and   
    (ii) EXECUTION phase that uses a session to execute ops in the graph   
10) Graph may be created with ops using no input but only CONSTANT and pass its output to other ops for computation   

### Notes:
1) Tensorflow python library has a DEFAULT Graph to which ops constructors add nodes.   
2) It is better to have disconnected subgraphs within a graph as data cannot be passed between them.   
3) Multiple graphs will need multiple sessions as each will try to use all resources by default.    

In [1]:
import numpy as np
import tensorflow as tf
print("Tensorflow version " + tf.__version__)
tf.set_random_seed(0)
sess = tf.Session()

Tensorflow version 1.3.0


###### Printing constant

In [2]:
temp = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])
result1 = tf.reshape(temp,[2,3,4])
result2 = tf.reshape(temp,[6,4])
result3 = tf.reshape(temp,[3,8])
print('result1 = \n' ,sess.run([result1]))
print('result2 = \n' ,sess.run([result2]))
print('result3 = \n' ,sess.run([result3]))
a = tf.constant([5, 6, 7])
print('a = ' , sess.run(a))

result1 = 
 [array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])]
result2 = 
 [array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])]
result3 = 
 [array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])]
a =  [5 6 7]


###### Reshaped tensors

In [3]:
result4 = tf.reshape(result1,[2,-1])
result5 = tf.reshape(result2,[2,-1])
result6 = tf.reshape(result3,[2,-1])
result7 = tf.reshape(result1,[-1,2])
result8 = tf.reshape(result2,[-1,2])
result9 = tf.reshape(result3,[-1,2])
result10 = tf.reshape(result1,[-1,2,2])
result11 = tf.reshape(result2,[2,-1,2])
result12 = tf.reshape(result3,[2,2,-1])
result13 = tf.reshape(result1,[-1])
print('result4 = \n', sess.run(result4))
print('result5 = \n', sess.run(result5))
print('result6 = \n', sess.run(result6))
print('result7 = \n', sess.run(result7))
print('result8 = \n', sess.run(result8))
print('result9 = \n', sess.run(result9))
print('result10 = \n', sess.run(result10))
print('result11 = \n', sess.run(result11))
print('result12 = \n', sess.run(result12))
print('result13 = \n', sess.run(result13))

result4 = 
 [[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
result5 = 
 [[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
result6 = 
 [[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
result7 = 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]]
result8 = 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]]
result9 = 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]]
result10 = 
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]

 [[21 22]
  [23 24]]]
result11 = 
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]
  [19 20]
  [21 22]
  [23 24]]]
result12 = 
 [[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
 

In [4]:
b, c, d = 2, 3, 4
x = tf.Variable(tf.random_normal([b, c, d], mean=0.0, stddev=1.0, dtype=tf.float32))
s = tf.shape(x)
init = tf.global_variables_initializer()
print('init = ' ,sess.run(init))

init =  None


###### Printing variables

In [5]:
print('x = \n', sess.run(x))
print('s = ', sess.run(s))
v1, v2, v3 = sess.run(s)
print('v1 = ' ,v1)
print('v2 = ' ,v2)
print('v3 = ' ,v3)

x = 
 [[[ 0.05296476 -0.59144998  0.21888156 -1.30634928]
  [ 0.07562245  0.54422814 -0.28945741 -2.4547255 ]
  [-0.13189495  1.16053343  1.09799862 -0.36790636]]

 [[-1.05851758  0.4055427  -0.55541044  1.30163646]
  [ 0.43623698  0.35988063 -0.2545971   0.54564393]
  [ 0.49471083 -0.02709649  1.40915966 -0.37623245]]]
s =  [2 3 4]
v1 =  2
v2 =  3
v3 =  4


###### Multiplication

In [6]:
matrix1 = tf.constant([[3,3]])#Op created as a 1*2 matrix
matrix2 = tf.constant([[2],[2]])#Op created as a 2*1 matrix
product = tf.matmul(matrix1,matrix2)#Graph has 3 nodes - 2 constant ops and 1 matmul op
sess = tf.Session()#Launches default graph
result = sess.run(product)#run() method creates a numpy ndarray object
print(result)
sess.close()#Close session when done

[[12]]


###### Interactive usage

In [7]:
sess = tf.InteractiveSession()#Launches default graph
matrix1 = tf.constant([[3.,3.]])#Op created as a 1*2 matrix
matrix2 = tf.constant([[2.],[2.]])#Op created as a 1*2 matrix
product = tf.matmul(matrix1,matrix2)
print(product.eval())#Interactive call makes sense with a variable as it avoids holding the variable throughout the run
sess.close()#Close session when done

[[ 12.]]


In [8]:
sess = tf.InteractiveSession()
x = tf.Variable([1.0,2.0])
a = tf.constant([3.0,3.0])
x.initializer.run()#x is initialised
sub = tf.subtract(x,a)
print(sub.eval())
sess.close()

[-2. -1.]


###### Executing code

In [9]:
state = tf.Variable(0, name="counter")
one = tf.constant(1)
new_value = tf.add(state, one)
update = tf.assign(state, new_value)
init_op = tf.global_variables_initializer()#Variables must be initialised through after launching the graph

with tf.Session() as sess:
    sess.run(init_op)
    print(sess.run(state))
    for each in range(3):
        print(sess.run(state))

0
0
0
0


###### More Tensor shape manipulations

In [10]:
sess = tf.Session()
temp = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])
#temp = np.arange(120)
result14 = tf.reshape(temp,[3,2,4])
print('result14 = \n' ,sess.run([result14]))
result15 = tf.slice(result14,[2, 1, 1], [1, 1, -1])
print('result15 = \n' ,sess.run([result15]))
result16 = tf.slice(result14, [0, 0, 0], [2, -1, 2])
print('result16 = \n' ,sess.run([result16]))
print('Dimension of result14 is larger than that of result16 by:' ,
      result14.get_shape().as_list()[0] - result16.get_shape().as_list()[0])
result17 = tf.slice(result14, [1, 0, 1], [1, 2, 2])
print('result17 = \n' ,sess.run([result17]))

result14 = 
 [array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])]
result15 = 
 [array([[[22, 23, 24]]])]
result16 = 
 [array([[[ 1,  2],
        [ 5,  6]],

       [[ 9, 10],
        [13, 14]]])]
Dimension of result14 is larger than that of result16 by: 1
result17 = 
 [array([[[10, 11],
        [14, 15]]])]


In [11]:
temp = np.arange(75)
result17 = tf.reshape(temp,[3,5,5])
print('result17 = \n' ,sess.run([result17]))
result18 = tf.reshape(result17,(3,-1))
print('result18 = \n' ,sess.run([result18]))
result19 = tf.transpose(result18)
print('result19 = \n' ,sess.run([result19]))
print('No. of channels or classes = ' +  str(result17.get_shape().as_list()[2]) + ',\n' + 
      'No. of columns in flattened array or classes = ' + str(result19.get_shape().as_list()[1]) + '\n')

result17 = 
 [array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]]])]
result18 = 
 [array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
        67, 68, 69, 70, 71, 72, 73, 74]])]
result19 = 
 [array([[ 0, 25, 50],
       [ 1, 26, 51],
       [ 2, 27, 52],
       [ 3, 28, 53],
       [ 4, 29, 54],
       [ 5, 30, 55],
       [ 6, 31, 56],
 

In [12]:
temp = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])
print('temp = \n' ,sess.run([temp]))
result20 = tf.reshape(temp,[2,3,4])
print('result20 = \n' ,sess.run([result20]))
print('Shape of result20 is: ',result20.get_shape().as_list())
result21 = tf.reshape(result20,[-1])
print('Shape of result20 is: ',result21.get_shape().as_list())

temp = 
 [array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])]
result20 = 
 [array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])]
Shape of result20 is:  [2, 3, 4]
Shape of result20 is:  [24]


In [13]:
temp1 = tf.constant([1,2,3,4,5])
temp2 = tf.constant([5,4,3,2,1])
result20 = tf.reduce_sum(temp1 * temp2)
print('result20 = \n' ,sess.run(result20))
print('Shape of temp1 is ',temp1.get_shape().as_list())

result20 = 
 35
Shape of temp1 is  [5]


In [14]:
sumTemp1 = tf.reduce_sum(temp1)
print('Shape of sumTemp1 is ',sumTemp1.get_shape().as_list())

Shape of sumTemp1 is  []


In [15]:
temp = tf.constant([[[1,2],[1,2],[1,2]],[[1,2],[1,2],[1,2]],[[1,2],[1,2],[1,2]]])
temp.get_shape().as_list()

[3, 3, 2]

In [16]:
params = tf.constant([[['a', 'b'], ['c', 'd']],
              [['e', 'f'], ['g', 'h']]])
print('params shape = ', params.get_shape().as_list())
indices = tf.constant([[[0, 0, 1], [1, 0, 1]], 
                       [[0, 1, 1], [1, 1, 0]]])
print('indices shape = ', indices.get_shape().as_list())
sliceoutput = tf.gather_nd(params, indices)
print('slice output is: ', sess.run(sliceoutput))

params shape =  [2, 2, 2]
indices shape =  [2, 2, 3]
slice output is:  [[b'b' b'f']
 [b'd' b'g']]


In [17]:
params = tf.constant([[['a', 'b'], ['c', 'd']],
              [['e', 'f'], ['g', 'h']]])
print('params shape = ', params.get_shape().as_list())
indices = tf.constant([[[0, 0], [1, 0]], 
                       [[0, 1], [1, 1]]])
print('indices shape = ', indices.get_shape().as_list())
sliceoutput = tf.gather_nd(params, indices)
print('slice output is: ', sess.run(sliceoutput))

params shape =  [2, 2, 2]
indices shape =  [2, 2, 2]
slice output is:  [[[b'a' b'b']
  [b'e' b'f']]

 [[b'c' b'd']
  [b'g' b'h']]]


In [18]:
params = tf.constant([[['a', 'b'], ['c', 'd']],
              [['e', 'f'], ['g', 'h']]])
print('params shape = ', params.get_shape().as_list())
indices = tf.constant([[0, 1], 
                       [0, 1]])
print('indices shape = ', indices.get_shape().as_list())
sliceoutput = tf.gather_nd(params, indices)
print('slice output is: ', sess.run(sliceoutput))

params shape =  [2, 2, 2]
indices shape =  [2, 2]
slice output is:  [[b'c' b'd']
 [b'c' b'd']]


In [19]:
params = tf.constant([[['a', 'b'], ['c', 'd']],
              [['e', 'f'], ['g', 'h']]])
print('params shape = ', params.get_shape().as_list())
indices = tf.constant([[[0, 0], [1, 0]], 
                       [[0, 1], [1, 1]]])
print('indices shape = ', indices.get_shape().as_list())
sliceoutput = tf.gather_nd(params, indices)
print('slice output is: ', sess.run(sliceoutput))

params shape =  [2, 2, 2]
indices shape =  [2, 2, 2]
slice output is:  [[[b'a' b'b']
  [b'e' b'f']]

 [[b'c' b'd']
  [b'g' b'h']]]


In [20]:
x = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
#x = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
y = tf.transpose(x, perm=[0, 2, 1])
z = tf.transpose(x, perm=[0, 1, 2])
print('y => ',sess.run(y))
print('z => ',sess.run(z))

y =>  [[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]
z =>  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [21]:
t1 = tf.constant([[[1,2,30],[2,3,4]],[[50,6,7],[7,8,9]]])
print('\nShape of t1 is: ', t1.get_shape().as_list())
t2 = tf.constant([[[10,2,3],[20,3,4]],[[5,6,7],[7,80,9]]])
print('\nShape of t2 is: ', t2.get_shape().as_list())

a1 = tf.argmax(t1,2)
print('\nShape of a1 is: ', a1.get_shape().as_list())
a2 = tf.argmax(t2,2)
print('\nShape of a2 is: ', a2.get_shape().as_list())

compBool = tf.equal(a1,a2)

r1 = tf.reduce_max(t1,2)
print('\nShape of r1 is: ', r1.get_shape().as_list())
r2 = tf.reduce_max(t2,2)
print('\nShape of r2 is: ', r2.get_shape().as_list())

print('\nShape after compBool is: ', compBool.get_shape().as_list())
#predClass = tf.where(compBool,r1,r2)
predClass = tf.where(compBool)
print('\nShape after predClass is: ', predClass.get_shape().as_list())

f1 = tf.reshape(r1,[-1])
print('\nShape after f1 is: ', f1.get_shape().as_list())
nr = tf.log(tf.cast(f1,tf.float32))
dr = tf.log(tf.constant(2,dtype=nr.dtype))
nd = -tf.reduce_sum(nr/dr)


Shape of t1 is:  [2, 2, 3]

Shape of t2 is:  [2, 2, 3]

Shape of a1 is:  [2, 2]

Shape of a2 is:  [2, 2]

Shape of r1 is:  [2, 2]

Shape of r2 is:  [2, 2]

Shape after compBool is:  [2, 2]

Shape after predClass is:  [None, 2]

Shape after f1 is:  [4]


In [22]:
#valueMatrix = tf.constant([[[7,15,5],[4,6,8]],[[70,150,50],[40,60,80]]])
#valueMatrix = tf.constant([[7,15,5],[4,6,8]])
#valueMatrix = tf.constant([[[7,15],[4,6]],[[70,150],[40,60]],[[7,15],[4,6]],[[70,150],[40,60]]])
#valueMatrix = tf.constant([[[7,15],[4,6]],[[70,150],[40,60]]])
valueMatrix = tf.constant([[[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]],
                           [[21,22,23,24,25],[26,27,28,29,30],[31,32,33,34,35],[36,37,38,39,40]],
                          [[41,42,43,44,45],[46,47,48,49,50],[51,52,53,54,55],[56,57,58,59,60]]],
                          [[[61,62,63,64,65],[66,67,68,69,70],[71,72,73,74,75],[76,77,78,79,80]],
                           [[81,82,83,84,85],[86,87,88,89,90],[91,92,93,94,95],[96,97,98,99,100]],
                           [[101,102,103,104,105],[106,107,108,109,110],[111,112,113,114,115],[116,117,118,119,120]]]])
indexMatrix = tf.constant([[1],[0]])
print('Shape of valueMatrix is: ', valueMatrix.get_shape().as_list())
# create the row index with tf.range
row_idx = tf.reshape(tf.range(indexMatrix.shape[0]), (-1,1))
# stack with column index
idx = tf.stack([row_idx, indexMatrix], axis=-1)
# extract the elements with gather_nd
values = tf.gather_nd(valueMatrix, idx)
#valuesShape = values.get_shape().as_list()
#idx_list = np.array([[0,2],[0,2]])
#idx_list = np.array([0,1,2,3,4])
#output = tf.transpose(tf.gather(tf.transpose(input),idx_list))
transp = tf.convert_to_tensor(tf.transpose(valueMatrix))
lastDim = tf.gather(transp,[4,3,2])
with tf.Session() as sess:
    print('Transpose ==> ',sess.run(transp))
    print('Shape of transpose = ',transp.get_shape().as_list())
    print('Last dimension of transpose ==> ',sess.run(lastDim))
    print('Original ==> ',sess.run(valueMatrix))
    print('Indexed ==> ',sess.run(values))
    #print('Computed indexed  ==> ',sess.run(output))
    #print('Shape of indexed = ',sess.run(final))

Shape of valueMatrix is:  [2, 3, 4, 5]
Transpose ==>  [[[[  1  61]
   [ 21  81]
   [ 41 101]]

  [[  6  66]
   [ 26  86]
   [ 46 106]]

  [[ 11  71]
   [ 31  91]
   [ 51 111]]

  [[ 16  76]
   [ 36  96]
   [ 56 116]]]


 [[[  2  62]
   [ 22  82]
   [ 42 102]]

  [[  7  67]
   [ 27  87]
   [ 47 107]]

  [[ 12  72]
   [ 32  92]
   [ 52 112]]

  [[ 17  77]
   [ 37  97]
   [ 57 117]]]


 [[[  3  63]
   [ 23  83]
   [ 43 103]]

  [[  8  68]
   [ 28  88]
   [ 48 108]]

  [[ 13  73]
   [ 33  93]
   [ 53 113]]

  [[ 18  78]
   [ 38  98]
   [ 58 118]]]


 [[[  4  64]
   [ 24  84]
   [ 44 104]]

  [[  9  69]
   [ 29  89]
   [ 49 109]]

  [[ 14  74]
   [ 34  94]
   [ 54 114]]

  [[ 19  79]
   [ 39  99]
   [ 59 119]]]


 [[[  5  65]
   [ 25  85]
   [ 45 105]]

  [[ 10  70]
   [ 30  90]
   [ 50 110]]

  [[ 15  75]
   [ 35  95]
   [ 55 115]]

  [[ 20  80]
   [ 40 100]
   [ 60 120]]]]
Shape of transpose =  [5, 4, 3, 2]
Last dimension of transpose ==>  [[[[  5  65]
   [ 25  85]
   [ 45 105]]

  [[ 10 